import type { ThemeDefinition } from './tableThemes.types'

export const TABLE_THEMES: ThemeDefinition[] = [
  {
    id: 'default',
    label: 'Default',
    headerBg: '#1E40AF',
    headerText: '#FFFFFF',
    rowBg: '#FFFFFF',
    altRowBg: '#FFFFFF',
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
  },
  {
    id: 'minimal',
    label: 'Minimal',
    headerBg: '#FFFFFF',
    headerText: '#111827',
    rowBg: '#FFFFFF',
    altRowBg: '#FFFFFF',
    borderStyle: 'solid',
    borderColor: '#F3F4F6',
  },
  {
    id: 'dark-header',
    label: 'Dark header',
    headerBg: '#1E293B',
    headerText: '#FFFFFF',
    rowBg: '#FFFFFF',
    altRowBg: '#F9FAFB',
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
  },
  {
    id: 'striped',
    label: 'Striped',
    headerBg: '#1E40AF',
    headerText: '#FFFFFF',
    rowBg: '#FFFFFF',
    altRowBg: '#F9FAFB',
    borderStyle: 'solid',
    borderColor: '#E5E7EB',
  },
  {
    id: 'academic',
    label: 'Academic',
    headerBg: '#F3F4F6',
    headerText: '#111827',
    rowBg: '#FFFFFF',
    altRowBg: '#FFFFFF',
    borderStyle: 'solid',
    borderColor: '#D1D5DB',
  },
  {
    id: 'monochrome',
    label: 'Monochrome',
    headerBg: '#374151',
    headerText: '#FFFFFF',
    rowBg: '#FFFFFF',
    altRowBg: '#F9FAFB',
    borderStyle: 'solid',
    borderColor: '#9CA3AF',
  },
]
