import type { PresetDefinition } from '../types/ui.types'

export const presets: PresetDefinition[] = [
  {
    id: 'schedule',
    label: 'Schedule',
    rows: 8,
    cols: 6,
    headerStyle: 'both',
    headers: [],
    data: [
      ['', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      ['9:00 AM', '', '', '', '', ''],
      ['10:00 AM', '', '', '', '', ''],
      ['11:00 AM', '', '', '', '', ''],
      ['12:00 PM', '', '', '', '', ''],
      ['1:00 PM', '', '', '', '', ''],
      ['2:00 PM', '', '', '', '', ''],
      ['3:00 PM', '', '', '', '', ''],
    ],
  },
  {
    id: 'checklist',
    label: 'Checklist',
    rows: 6,
    cols: 3,
    headerStyle: 'first-row',
    headers: ['Task', 'Status', 'Notes'],
    data: [
      ['Task', 'Status', 'Notes'],
      ['Research', 'Not started', ''],
      ['Draft', 'In progress', ''],
      ['Review', 'Pending', ''],
      ['Publish', 'Pending', ''],
      ['Follow up', 'Pending', ''],
    ],
  },
  {
    id: 'pricing',
    label: 'Pricing Table',
    rows: 6,
    cols: 4,
    headerStyle: 'both',
    headers: [],
    data: [
      ['', 'Basic', 'Pro', 'Enterprise'],
      ['Price', '$19', '$49', 'Custom'],
      ['Users', '1', '5', 'Unlimited'],
      ['Storage', '10 GB', '100 GB', '1 TB'],
      ['Support', 'Email', 'Priority', 'Dedicated'],
      ['Best for', 'Starters', 'Teams', 'Companies'],
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory',
    rows: 6,
    cols: 5,
    headerStyle: 'first-row',
    headers: ['Item', 'SKU', 'Quantity', 'Unit Price', 'Total'],
    data: [
      ['Item', 'SKU', 'Quantity', 'Unit Price', 'Total'],
      ['Notebook', 'NB-104', '24', '$6.50', '$156.00'],
      ['Pen Set', 'PN-220', '48', '$3.25', '$156.00'],
      ['Desk Lamp', 'DL-088', '12', '$22.00', '$264.00'],
      ['Folders', 'FD-010', '60', '$1.10', '$66.00'],
      ['', '', '', '', ''],
    ],
  },
]
