import { exportFormats } from './export/exportConfig'
import { headerColorSwatches, contentColorSwatches } from './colorPalette'

export const siteConfig = {
  brand: {
    name: 'Tablesmit',
    alternateName: 'Tablesmith',
    tagline: 'Tables, your way.',
    description:
      'A minimalist table builder for analytical writing. With full control over headers, formatting, and export.',
    metaDescription:
      'Build clean, structured tables with full control over headers, formatting, and export. Free. No signup. Export to PDF, Excel, CSV, or PNG.',
    url: 'https://tablesmit.com',
    githubUrl: 'https://github.com/Olayiwola72/tablesmit',
    contactEmail: 'hello@tablesmit.com',
    defaultAuthor: 'Olayiwola Akinnagbe',
    authorTwitter: 'https://x.com/OlayiwolaAkinn1',
  },
  exportFileBaseName: 'tablesmit-table',
  exports: exportFormats,
  colors: {
    defaultHeader: '#1E293B',
    defaultContent: '#111827',
    header: headerColorSwatches,
    content: contentColorSwatches,
  },
  columnFormats: [
    { value: 'text', label: 'Text' },
    { value: 'number', label: 'Number' },
    { value: 'currency', label: 'Currency' },
    { value: 'percentage', label: 'Percentage' },
    { value: 'date', label: 'Date' },
    { value: 'sum', label: 'Sum' },
    { value: 'auto-number', label: '#' },
  ],
  routes: {
    home: '/',
    about: '/about',
    blog: '/blog',
    blogPost: '/blog/:slug',
    features: '/features',
    featureDetail: '/features/:slug',
    contact: '/contact',
    openSource: '/open-source',
    privacy: '/privacy',
    terms: '/terms',
    changelog: '/changelog',
    testimonials: '/testimonials',
  },
  sponsors: [
    {
      id: 'github',
      label: 'GitHub Sponsors',
      description: 'Sponsor monthly on GitHub',
      url: 'https://github.com/sponsors/Olayiwola72',
      cta: 'Sponsor on GitHub',
    },
    {
      id: 'bmac',
      label: 'Buy Me a Coffee',
      description: 'One-time contribution',
      url: 'https://buymeacoffee.com/Olayiwola72',
      cta: 'Buy a coffee',
    },
    {
      id: 'opencollective',
      label: 'Open Collective',
      description: 'For teams and organizations',
      url: 'https://opencollective.com/tablesmit',
      cta: 'Contribute',
    },
  ],
  nav: [
    { label: 'Home', route: 'home' },
    { label: 'About', route: 'about' },
    { label: 'Features', route: 'features' },
    { label: 'Blog', route: 'blog' },
    { label: 'Contact', route: 'contact' },
    { label: 'Open Source', route: 'openSource' },
    { label: 'Changelog', route: 'changelog' },
    { label: 'Testimonials', route: 'testimonials' },
  ],
  copy: {
    heroHeadlineLine1: 'Tables built for',
    heroHeadlineLine2: 'analytical writing.',
    heroSubtext:
      'A minimalist table builder for analytical writing, with full control over headers, formatting, and export.',
    tableMakerHeadline: 'Tables built for analytical writing.',
    tableMakerSubtext: 'Full control over headers, formatting, and export.',
    openSourceHeading: 'Built in the open.',
    openSourceBody:
      'Tablesmit is free and open source. The code is on GitHub. Read it, fork it, improve it, or adapt it for your own needs. We believe tools for writing and thinking should be transparent.',
    aboutHeading: 'Built for structured thinkers.',
    aboutOrigin:
      'Tablesmit was created by a writer who needed more control than basic table generators provided.',
    aboutTooLittle:
      'Most tools gave too little: no header customization, no column formatting, no clean export. Others gave too much: the full weight of a spreadsheet for something that just needed to be a table.',
    aboutMiddleGround:
      'Tablesmit is the middle ground. Built for people who think in structure and publish with precision.',
    whatWeAreNotHeading: 'What Tablesmit Is Not',
    whatWeAreNot: [
      'Not a spreadsheet.',
      'Not a database.',
      'Not a Notion competitor.',
      'Not a design-heavy tool.',
    ],
    positioningClosing: 'We are a structured writing tool.',
    openSourcePageHero: 'Built in the open. Sustained by the community.',
    openSourcePageBody:
      'Tablesmit is free and open source. The code is on GitHub. Read it, fork it, improve it, or adapt it for your own needs. We believe tools for writing and thinking should be transparent.',
    sponsorBody:
      'Tablesmit is maintained in the open. If the tool helps you write better tables, consider sponsoring. It keeps the project sustainable and focused.',
    spreadTheWord:
      'Share Tablesmit with someone who needs a better table tool. Stars on GitHub help others find it too.',
    contactIntro:
      'Tablesmit is built by one person who cares about getting the details right. Every email, every suggestion, every bug report shapes what this tool becomes.',
    contactCommunity:
      'You are not just a user. You are part of how Tablesmit grows.',
    contactThanks:
      'Tablesmit is open source and free. Every contributor, every issue filed, every kind word matters. Thank you for being here.',
    contactHiReason: 'Stumbled on Tablesmit and want to share your thoughts? I would love to hear them.',
  },
  labels: {

    gridSize: 'Grid Size',
    rows: 'Rows',
    columns: 'Columns',
    createTable: 'Create Table',
    headerDefinitions: 'Header Definitions',
    headerStyle: 'Header Style',
    headerStyleOptions: [
      { value: 'none', label: 'No Header' },
      { value: 'first-row', label: 'First Row' },
      { value: 'first-column', label: 'First Column' },
      { value: 'both', label: 'Both' },
    ] as const,
    columnType: 'Column Type',
    templates: 'Templates',
    exportOptions: 'Export Options',
    mergeCells: 'Merge Cells',
    merge: 'Merge',
    unmerge: 'Unmerge',
    noSelection: 'No selection',
    colors: 'Colors',
    header: 'Header',
    content: 'Content',
    mergeInstructions: 'Click a cell, then Shift-click another cell to select a merge range.',
    tableTheme: 'Table Theme',
    borderStyle: 'Border Style',
    borderColor: 'Border Color',
    rowColor: 'Row Color',
    removeRowColor: 'Remove row color',
    borderStyles: [
      { value: 'none', label: 'None' },
      { value: 'solid', label: 'Solid' },
      { value: 'dotted', label: 'Dotted' },
      { value: 'dashed', label: 'Dashed' },
      { value: 'double', label: 'Double' },
    ] as const,
    addRow: 'Add Row',
    addColumn: 'Add Column',
    removeRow: 'Remove Row',
    removeColumn: 'Remove Column',
    clearAll: 'Clear All',
    undo: 'Undo',
    tooltipMerge: 'Merge selected cells',
    templatesLabel: 'Templates',
    importLabel: 'Import',
    importCsv: 'Import from CSV',
    importExcel: 'Import from Excel',
    shortcutsHint: 'Ctrl+/ for shortcuts',
    autoFitColumn: 'Double-click a column border to AutoFit width',
    autoFitRow: 'Double-click to AutoFit row height',
    mergeAnnounce: 'Cells merged.',
    unmergeAnnounce: 'Cells unmerged.',
    cannotMergeSingleCell: 'Cannot merge a single cell. Select a range of cells first.',
    noMergeInSelection: 'No merge found in the selected range.',
    loading: 'Loading\u2026',
    contextAutoFit: 'Auto-fit column',
    contextColumnBackground: 'Column background',
    contextCellBackground: 'Cell background',
    contextColumnType: 'Column type',
    contextTextAlign: 'Text alignment',
    contextPaste: 'Paste',
    contextInsertRowAbove: 'Insert row above',
    contextInsertRowBelow: 'Insert row below',
    contextInsertColLeft: 'Insert column left',
    contextInsertColRight: 'Insert column right',
    contextDeleteRow: 'Delete row',
    contextDeleteCol: 'Delete column',
    contextClearCell: 'Clear cell',
    contextRemoveColor: 'Remove color',
    textAlignOptions: [
      { value: 'left', label: 'Left' },
      { value: 'center', label: 'Center' },
      { value: 'right', label: 'Right' },
    ] as const,
    copyTable: 'Copy Table',
    copyAsExcelData: 'Copy as Excel Data',
    copyAsCsv: 'Copy as CSV',
    copyAsMarkdown: 'Copy as Markdown',
    copyAsImage: 'Copy as Image',
    aiFeatures: 'AI Features (Beta)',
    comingSoon: 'Coming soon',
    aiFeatureList: ['Generate from text', 'Summarize', 'Clean data'],
    aiFeatureNote: 'AI features are in development. Join the waitlist.',
    joinWaitlist: 'Join Waitlist',
    aiToolbar: 'AI',
    importCleanData: 'Clean messy data',
    tableCaptionPlaceholder: 'Add a table title or caption (optional)',
    sortAscending: 'Sort ascending',
    sortDescending: 'Sort descending',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
  },
  messages: {
    importTooLarge: 'File too large. Maximum size is 5MB.',
    importParseError: 'Could not read file. Check the format and try again.',
  },
  locale: {
    date: 'en-US',
    currency: 'en-US',
    number: 'en-US',
    percent: 'en-US',
    currencyCode: 'USD',
    dateMonth: 'short' as const,
    dateDay: '2-digit' as const,
    dateYear: 'numeric' as const,
  },
  importLimits: {
    maxSizeMb: 5,
  },
} as const

export function brandHomeAriaLabel(): string {
  return `${siteConfig.brand.name} home`
}
