name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Husky
        run: npm run prepare

      - name: Test
        run: npm run test

      - name: Audit
        run: npm run audit

      - name: Build
        run: npm run build --if-present

      - name: Deploy to Netlify
        if: github.ref == 'refs/heads/main'
        run: |
          curl "$deploy_url"
        env:
          deploy_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
